---
name: App-War
version: 0.01
author:
  - 'John Trammell <johntrammell@gmail.com>'
abstract: turn one big decision into many small decisions
license: perl
requires:
  Carp: 0
  Data::Dumper: 0
  perl: 0
  strict: 0
  warnings: 0
build_requires:
  Module::Build::Compat: 0
  Test::More: 0
  Test::Script: 1.06
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  App::War:
    file: lib/App/War.pm
    version: 0.01
resources:
  license: ~
