---
name: App-War
version: 0.01
author:
  - 'John Trammell <johntrammell@gmail.com>'
abstract: turn one big decision into many small decisions
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Module::Build::Compat: 0
  Test::More: 0
  Test::Script: 1.06
  strict: 0
  warnings: 0
requires:
  Carp: 0
  Data::Dumper: 0
  perl: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.35
provides:
  App::War:
    file: lib/App/War.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
