#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';
use App::War;
use Getopt::Long;
use Pod::Usage;

our $VERSION = $App::War::VERSION;

=pod

=head1 NAME

war - break one big decision into lots of little decisions

=head1 SYNOPSIS

    war [-h|--help] [--man] [--version]
    war <sourcefile>

=head1 DESCRIPTION

FIXME

=head1 OPTIONS

=head2 -h, --help

FIXME

=head2 --man

FIXME

=cut

our %OPT = ();
my @OPTIONS = qw/ help|h man version|v /;
GetOptions(\%OPT,@OPTIONS) || pod2usage;
if ($OPT{version}) { die "Using App::War v$VERSION\n" }
if ($OPT{man}) { pod2usage(-verbose => 2); }
if ($OPT{help} || !@ARGV) { pod2usage(-exitval => 0); }

# get items
my @items = _items(shift);

# fight the war
my $war = App::War->new(items => \@items)->run;

# print the results
print $war->report;

# read the items from the file specified on the command line
sub _items {
    my $file = shift;
    open(my $h,q(<),$file) or die $!;
    return grep { /\S/ && !/^#/ } map { chomp; $_ } <$h>;
}

